GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Second blog",
    "author": "Macguire",
    "url": "https://www.youtube.com",
    "likes": 10
}

###
GET http://localhost:3003/api/blogs/66410a0371dd1b345ec2bca1 HTTP/1.1

###
DELETE http://localhost:3003/api/blogs/6637dcadbd0dbc8c594a77fc HTTP/1.1
